[package]
name = "captacao-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.26"
headless_chrome = "1.0.5"
playwright = "0.0.20"
selenium-rs = "0.1.2"
tokio = "1.25.0"
